import React, { useEffect } from 'react'
import { Modal, Form, Input as AntInput, Select, DatePicker, Switch, ConfigProvider, Spin } from 'antd'
import { GraduationCap, Calendar, Sparkles, Loader2, Calendar1 } from 'lucide-react'
import dayjs from 'dayjs'
import { toast } from 'sonner'
import { $api } from '../../../../api/client'

const { RangePicker } = DatePicker

interface ModalCreateDotHocPhiProps {
  isOpen: boolean
  onClose: () => void
  tuitionId?: number
  onSuccess?: () => void
}

interface FormValues {
  name: string
  semesterId: number
  dateRange: [dayjs.Dayjs, dayjs.Dayjs]
  isActive: boolean
}

const ModalCreateDotHocPhi: React.FC<ModalCreateDotHocPhiProps> = ({
  isOpen,
  onClose,
  tuitionId,
  onSuccess,
}) => {
  const [form] = Form.useForm<FormValues>()
  const isUpdateMode = !!tuitionId
  const isActiveWatch = Form.useWatch('isActive', form)

  // 1. Fetch chi tiết (Update Mode)
  const { data: dotHocPhiOne, isPending: isPendingFetch } = $api.useQuery(
    'get',
    '/tuition-periods/{id}',
    { params: { path: { id: tuitionId! } } },
    { enabled: isUpdateMode && isOpen },
  )

  // 2. Fetch danh sách học kỳ
  const { data: semesters, isLoading: isLoadingSemesters } = $api.useQuery(
    'get',
    '/semesters',
    {},
    { enabled: isOpen },
  )

  // 3. Mutations
  const { mutate: createDotHocPhi, isPending: isPendingCreate } = $api.useMutation('post', '/tuition-periods')

  const { mutate: updateDotHocPhi, isPending: isPendingUpdate } = $api.useMutation(
    'patch',
    '/tuition-periods/{id}',
  )

  const isSubmitting = isPendingCreate || isPendingUpdate

  // Sync dữ liệu vào Form
  useEffect(() => {
    if (!isOpen) return

    if (isUpdateMode && dotHocPhiOne) {
      form.setFieldsValue({
        name: dotHocPhiOne.name ?? '',
        semesterId: dotHocPhiOne.semesterId ? Number(dotHocPhiOne.semesterId) : undefined,
        dateRange:
          dotHocPhiOne.startDate && dotHocPhiOne.endDate
            ? [dayjs(dotHocPhiOne.startDate), dayjs(dotHocPhiOne.endDate)]
            : undefined,
        isActive: dotHocPhiOne.isActive ?? true,
      })
    } else if (!isUpdateMode) {
      form.resetFields()
      form.setFieldsValue({ isActive: true })
    }
  }, [isOpen, isUpdateMode, dotHocPhiOne, form])

  // Handle Submit Form
  const handleSubmit = async (values: FormValues) => {
    const payload = {
      name: values.name.trim(),
      semesterId: values.semesterId,
      startDate: values.dateRange[0].toDate(),
      endDate: values.dateRange[1].toDate(),
      isActive: values.isActive,
    }

    if (isUpdateMode) {
      updateDotHocPhi(
        {
          params: { path: { id: tuitionId! } },
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          body: payload as any,
        },
        {
          onSuccess: () => {
            toast.success('Cập nhật đợt học phí thành công!')
            onSuccess?.()
            onClose()
          },
          onError: () => {
            toast.error('Cập nhật đợt học phí thất bại!')
          },
        },
      )
    } else {
      createDotHocPhi(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        { body: payload as any },
        {
          onSuccess: () => {
            toast.success('Tạo mới đợt học phí thành công!')
            onSuccess?.()
            onClose()
          },
          onError: () => {
            toast.error('Tạo mới đợt học phí thất bại!')
          },
        },
      )
    }
  }

  // Hàm xử lý tự động điền tên đợt học phí khi chọn học kỳ
  const handleSemesterChange = (selectedSemesterId: number) => {
    const selectedSem = semesters?.find((sem) => Number(sem.id) === selectedSemesterId)
    if (selectedSem) {
      // Tự sinh tên dạng: "Đợt học phí <Tên học kỳ>"
      const autoGeneratedName = `Đợt học phí ${selectedSem.name}`

      // Đặt giá trị cho field "name"
      form.setFieldsValue({ name: autoGeneratedName })

      // Trigger validate lại field "name" để xóa lỗi (nếu trước đó bị rỗng)
      form.validateFields(['name'])
    }
  }

  return (
    <ConfigProvider
      theme={{
        token: {
          colorPrimary: '#2563eb',
          borderRadius: 10,
          fontSize: 14,
          fontFamily: 'inherit',
          colorBorder: '#ccc', // Viền mặc định: xám đậm hơn (Slate-300 thay vì xám nhạt)
          colorBorderSecondary: '#94a3b8', // Viền thứ cấp/RangePicker
          colorPrimaryHover: '#1d4ed8',
        },
        components: {
          Input: {
            controlHeight: 42,
            activeBorderColor: '#2563eb',
          },
          Select: {
            controlHeight: 42,
          },
          DatePicker: {
            controlHeight: 42,
          },
        },
      }}
    >
      <Modal
        open={isOpen}
        onCancel={onClose}
        onOk={() => form.submit()}
        confirmLoading={isSubmitting}
        okText={isUpdateMode ? 'Cập nhật' : 'Tạo mới'}
        cancelText="Hủy"
        width={520}
        centered
        destroyOnClose
        maskClosable={!isSubmitting}
        className="custom-ant-modal"
        title={
          <div className="flex items-center gap-3 border-b border-slate-100 pr-6 pb-2">
            <div className="flex items-center justify-center rounded-xl bg-blue-50 p-2.5 text-blue-600">
              <Sparkles className="h-5 w-5" />
            </div>
            <div>
              <h3 className="text-base leading-tight font-semibold text-slate-800">
                {isUpdateMode ? 'Cập nhật đợt học phí' : 'Tạo đợt học phí mới'}
              </h3>
              <p className="mt-0.5 text-xs font-normal text-slate-400">
                {isUpdateMode
                  ? 'Điều chỉnh thông tin và thời gian áp dụng'
                  : 'Thiết lập thông tin đợt thu học phí cho sinh viên'}
              </p>
            </div>
          </div>
        }
      >
        <div className="pt-4">
          {isUpdateMode && isPendingFetch ? (
            <div className="flex flex-col items-center justify-center space-y-3 py-12">
              <Loader2 className="h-8 w-8 animate-spin text-blue-600" />
              <p className="text-sm font-medium text-slate-500">Đang tải dữ liệu đợt học phí...</p>
            </div>
          ) : (
            <Form
              form={form}
              layout="vertical"
              onFinish={handleSubmit}
              requiredMark={false}
              className="space-y-1"
            >
              {/* Tên đợt học phí */}
              <Form.Item
                label={
                  <span className="text-sm font-medium text-slate-700">
                    Tên đợt học phí <span className="text-red-500">*</span>
                  </span>
                }
                name="name"
                rules={[
                  { required: true, message: 'Vui lòng nhập tên đợt học phí' },
                  { whitespace: true, message: 'Tên không được chỉ chứa khoảng trắng' },
                ]}
              >
                <AntInput
                  prefix={<Calendar1 className="mr-1 h-4 w-4 text-slate-400" />}
                  placeholder="Ví dụ: Học phí HK1 - Đợt 1 (2025-2026)"
                  allowClear
                />
              </Form.Item>

              {/* Chọn học kỳ */}
              <Form.Item
                label={
                  <span className="text-sm font-medium text-slate-700">
                    Học kỳ áp dụng <span className="text-red-500">*</span>
                  </span>
                }
                name="semesterId"
                rules={[{ required: true, message: 'Vui lòng chọn học kỳ' }]}
              >
                <Select
                  placeholder="-- Chọn học kỳ --"
                  loading={isLoadingSemesters}
                  notFoundContent={
                    isLoadingSemesters ? <Spin size="small" /> : 'Không tìm thấy học kỳ phù hợp'
                  }
                  onChange={handleSemesterChange}
                  suffixIcon={<GraduationCap className="h-4 w-4 text-slate-400" />}
                  options={(() => {
                    if (!semesters) return []

                    // 1. Lấy tất cả học kỳ ACTIVE
                    const activeSemesters = semesters.filter((sem) => sem.status === 'ACTIVE')

                    // 2. Lấy tối đa 3 học kỳ UPCOMING tiếp theo
                    const upcomingSemesters = semesters.filter((sem) => sem.status === 'UPCOMING').slice(0, 3)

                    // 3. Gộp lại và map thành options có tag trạng thái
                    return [...activeSemesters, ...upcomingSemesters].map((sem) => {
                      const isActive = sem.status === 'ACTIVE'

                      return {
                        label: (
                          <div className="flex w-full items-center justify-between">
                            <span>{sem.name}</span>
                            <span
                              className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${
                                isActive
                                  ? 'border border-emerald-200 bg-emerald-50 text-emerald-600'
                                  : 'border border-amber-200 bg-amber-50 text-amber-600'
                              }`}
                            >
                              {isActive ? 'Đang diễn ra' : 'Sắp tới'}
                            </span>
                          </div>
                        ),
                        // Giá trị dùng để tìm kiếm (search theo tên + trạng thái)
                        searchValue: `${sem.name} ${isActive ? 'Đang diễn ra' : 'Sắp tới'}`,
                        value: Number(sem.id),
                      }
                    })
                  })()}
                  showSearch
                  optionFilterProp="searchValue"
                />
              </Form.Item>

              {/* Thời gian Bắt đầu - Kết thúc (Chỉ chọn Ngày) */}
              <Form.Item
                label={
                  <span className="text-sm font-medium text-slate-700">
                    Thời hạn thu học phí <span className="text-red-500">*</span>
                  </span>
                }
                name="dateRange"
                rules={[
                  {
                    required: true,
                    type: 'array',
                    message: 'Vui lòng chọn thời gian bắt đầu và kết thúc',
                  },
                ]}
              >
                <RangePicker
                  className="w-full"
                  format="DD/MM/YYYY"
                  placeholder={['Ngày bắt đầu', 'Ngày kết thúc']}
                  suffixIcon={<Calendar className="h-4 w-4 text-slate-400" />}
                />
              </Form.Item>

              {/* Trạng thái Kích hoạt */}
              <div className="pt-2">
                <Form.Item name="isActive" valuePropName="checked" className="mb-0">
                  <div className="flex items-center justify-between rounded-xl border border-slate-200/80 bg-slate-50/80 p-3.5 transition-colors hover:border-slate-300">
                    <div className="flex flex-col pr-4">
                      <span className="text-sm font-semibold text-slate-700">Kích hoạt ngay</span>
                      <span className="mt-0.5 text-xs text-slate-500">
                        Cho phép áp dụng và hiển thị đợt học phí này trên hệ thống
                      </span>
                    </div>
                    <Switch
                      checked={isActiveWatch}
                      onChange={(checked) => form.setFieldValue('isActive', checked)}
                    />
                  </div>
                </Form.Item>
              </div>
            </Form>
          )}
        </div>
      </Modal>
    </ConfigProvider>
  )
}

export default ModalCreateDotHocPhi
