import type { DiemSinhVien } from "../type";

export const INITIAL_DATA: DiemSinhVien[] = [
  {
    id: 1,
    mssv: "SV001",
    hoTen: "Nguyễn Văn A",
    monHoc: "Lập trình React Native",
    chuyenCan: 10,
    thuongKy: 10,
    gk: 8.5,
    ck: 3.0,
    trangThai: "Chờ duyệt",
    daChot: false,
  },
  {
    id: 2,
    mssv: "SV002",
    hoTen: "Trần Thị B",
    monHoc: "Lập trình React Native",
    chuyenCan: 9,
    thuongKy: 8,
    gk: 7.0,
    ck: 6.5,
    trangThai: "Đã duyệt",
    daChot: true,
  },
  {
    id: 3,
    mssv: "SV003",
    hoTen: "Lê Hoàng C",
    monHoc: "Lập trình React Native",
    chuyenCan: 8,
    thuongKy: 9,
    gk: 6.5,
    ck: 5.5,
    trangThai: "Cần chỉnh sửa",
    daChot: false,
  },
  {
    id: 4,
    mssv: "SV004",
    hoTen: "Phạm Minh D",
    monHoc: "Lập trình React Native",
    chuyenCan: 7,
    thuongKy: 7,
    gk: 5.0,
    ck: 4.0,
    trangThai: "Đã khóa",
    daChot: true,
  },
  {
    id: 5,
    mssv: "SV005",
    hoTen: "Hoàng Thị E",
    monHoc: "Lập trình React Native",
    chuyenCan: 10,
    thuongKy: 10,
    gk: 9.5,
    ck: 9.0,
    trangThai: "Đã duyệt",
    daChot: false,
  },
];
