import type { CurriculumFramework } from "./chuongTrinhKhung.type";

export const mockData: CurriculumFramework[] = [
  {
    id: "1",
    code: "CTK-CĐ-CNTT-2024",
    name: "Công nghệ thông tin",
    major: "Công nghệ thông tin",
    eduSystem: "cao_dang",
    department: "Khoa CNTT",
    totalUnits: 90,
    unitType: "tin_chi",
    duration: "3 năm",
    status: "active",
    effectiveYear: 2024,
    issuedBy: "Bộ LĐTBXH",
    decisionNo: "2713/QĐ-BLĐTBXH",
    createdAt: "2024-01-10",
    updatedAt: "2024-06-01",
    terms: [
      {
        id: 1,
        label: "Học kỳ 1",
        modules: [
          {
            id: "m1",
            code: "MH01",
            name: "Giáo dục chính trị",
            units: 2,
            unitType: "tin_chi",
            theory: 30,
            practice: 0,
            type: "chung",
            semester: 1,
          },
          {
            id: "m2",
            code: "MH02",
            name: "Pháp luật",
            units: 1,
            unitType: "tin_chi",
            theory: 15,
            practice: 0,
            type: "chung",
            semester: 1,
          },
          {
            id: "m3",
            code: "MH03",
            name: "Giáo dục thể chất",
            units: 1,
            unitType: "tin_chi",
            theory: 0,
            practice: 30,
            type: "chung",
            semester: 1,
          },
          {
            id: "m4",
            code: "MĐ04",
            name: "Tin học văn phòng",
            units: 3,
            unitType: "tin_chi",
            theory: 15,
            practice: 60,
            type: "co_so",
            semester: 1,
          },
          {
            id: "m5",
            code: "MĐ05",
            name: "Lập trình căn bản",
            units: 4,
            unitType: "tin_chi",
            theory: 30,
            practice: 90,
            type: "co_so",
            semester: 1,
            isKey: true,
          },
          {
            id: "m6",
            code: "MH06",
            name: "Tiếng Anh 1",
            units: 3,
            unitType: "tin_chi",
            theory: 30,
            practice: 30,
            type: "chung",
            semester: 1,
          },
        ],
      },
      {
        id: 2,
        label: "Học kỳ 2",
        modules: [
          {
            id: "m7",
            code: "MĐ07",
            name: "Lập trình hướng đối tượng",
            units: 4,
            unitType: "tin_chi",
            theory: 30,
            practice: 90,
            type: "chuyen_mon",
            semester: 2,
            prerequisite: ["MĐ05"],
            isKey: true,
          },
          {
            id: "m8",
            code: "MĐ08",
            name: "Cơ sở dữ liệu",
            units: 3,
            unitType: "tin_chi",
            theory: 30,
            practice: 60,
            type: "co_so",
            semester: 2,
            isKey: true,
          },
          {
            id: "m9",
            code: "MĐ09",
            name: "Mạng máy tính cơ bản",
            units: 3,
            unitType: "tin_chi",
            theory: 30,
            practice: 45,
            type: "co_so",
            semester: 2,
          },
          {
            id: "m10",
            code: "MH10",
            name: "Tiếng Anh 2",
            units: 3,
            unitType: "tin_chi",
            theory: 30,
            practice: 30,
            type: "chung",
            semester: 2,
            prerequisite: ["MH06"],
          },
        ],
      },
      {
        id: 3,
        label: "Học kỳ 3",
        modules: [
          {
            id: "m12",
            code: "MĐ12",
            name: "Lập trình Web Frontend",
            units: 4,
            unitType: "tin_chi",
            theory: 30,
            practice: 90,
            type: "chuyen_mon",
            semester: 3,
            prerequisite: ["MĐ07"],
            isKey: true,
          },
          {
            id: "m13",
            code: "MĐ13",
            name: "Thiết kế cơ sở dữ liệu",
            units: 3,
            unitType: "tin_chi",
            theory: 30,
            practice: 60,
            type: "chuyen_mon",
            semester: 3,
          },
          {
            id: "m14",
            code: "MĐ14",
            name: "Lập trình Java",
            units: 4,
            unitType: "tin_chi",
            theory: 30,
            practice: 90,
            type: "tu_chon",
            semester: 3,
          },
        ],
      },
      {
        id: 4,
        label: "Học kỳ 4",
        modules: [
          {
            id: "m16",
            code: "MĐ16",
            name: "Lập trình Web Backend (Node.js)",
            units: 4,
            unitType: "tin_chi",
            theory: 30,
            practice: 90,
            type: "chuyen_mon",
            semester: 4,
            prerequisite: ["MĐ12"],
            isKey: true,
          },
          {
            id: "m17",
            code: "MĐ17",
            name: "Kiểm thử phần mềm",
            units: 3,
            unitType: "tin_chi",
            theory: 15,
            practice: 75,
            type: "chuyen_mon",
            semester: 4,
          },
          {
            id: "m18",
            code: "MĐ18",
            name: "Quản lý dự án phần mềm",
            units: 2,
            unitType: "tin_chi",
            theory: 30,
            practice: 0,
            type: "chuyen_mon",
            semester: 4,
          },
        ],
      },
      {
        id: 5,
        label: "Học kỳ 5 – Thực tập",
        internship: true,
        modules: [
          {
            id: "m19",
            code: "TT01",
            name: "Thực tập tốt nghiệp tại doanh nghiệp",
            units: 8,
            unitType: "tin_chi",
            theory: 0,
            practice: 360,
            type: "thuc_tap",
            semester: 5,
            isKey: true,
          },
          {
            id: "m20",
            code: "DA01",
            name: "Đồ án tốt nghiệp",
            units: 4,
            unitType: "tin_chi",
            theory: 0,
            practice: 180,
            type: "thuc_tap",
            semester: 5,
          },
        ],
      },
    ],
  },
  {
    id: "2",
    code: "CTK-TC-KT-2024",
    name: "Kế toán doanh nghiệp",
    major: "Kế toán doanh nghiệp",
    eduSystem: "trung_cap",
    department: "Khoa Kinh tế",
    totalUnits: 65,
    unitType: "tin_chi",
    duration: "2 năm",
    status: "active",
    effectiveYear: 2024,
    issuedBy: "Bộ LĐTBXH",
    decisionNo: "3144/QĐ-BLĐTBXH",
    createdAt: "2024-02-01",
    updatedAt: "2024-07-10",
    terms: [
      {
        id: 1,
        label: "Học kỳ 1",
        modules: [
          {
            id: "k1",
            code: "MH01",
            name: "Giáo dục chính trị",
            units: 2,
            unitType: "tin_chi",
            theory: 30,
            practice: 0,
            type: "chung",
            semester: 1,
          },
          {
            id: "k2",
            code: "MĐ02",
            name: "Nguyên lý kế toán",
            units: 3,
            unitType: "tin_chi",
            theory: 30,
            practice: 45,
            type: "co_so",
            semester: 1,
            isKey: true,
          },
          {
            id: "k3",
            code: "MĐ03",
            name: "Tin học kế toán",
            units: 3,
            unitType: "tin_chi",
            theory: 15,
            practice: 75,
            type: "co_so",
            semester: 1,
            isKey: true,
          },
          {
            id: "k4",
            code: "MH04",
            name: "Kinh tế vi mô",
            units: 2,
            unitType: "tin_chi",
            theory: 30,
            practice: 0,
            type: "co_so",
            semester: 1,
          },
        ],
      },
      {
        id: 2,
        label: "Học kỳ 2",
        modules: [
          {
            id: "k5",
            code: "MĐ05",
            name: "Kế toán tài chính 1",
            units: 4,
            unitType: "tin_chi",
            theory: 30,
            practice: 90,
            type: "chuyen_mon",
            semester: 2,
            prerequisite: ["MĐ02"],
            isKey: true,
          },
          {
            id: "k6",
            code: "MĐ06",
            name: "Thuế",
            units: 3,
            unitType: "tin_chi",
            theory: 30,
            practice: 45,
            type: "chuyen_mon",
            semester: 2,
            isKey: true,
          },
          {
            id: "k7",
            code: "MĐ07",
            name: "Phần mềm kế toán MISA",
            units: 3,
            unitType: "tin_chi",
            theory: 10,
            practice: 80,
            type: "thuc_hanh",
            semester: 2,
            isKey: true,
          },
        ],
      },
      {
        id: 3,
        label: "Thực tập nghề",
        internship: true,
        modules: [
          {
            id: "k8",
            code: "TT01",
            name: "Thực tập nghề kế toán tại doanh nghiệp",
            units: 6,
            unitType: "tin_chi",
            theory: 0,
            practice: 270,
            type: "thuc_tap",
            semester: 3,
            isKey: true,
          },
        ],
      },
    ],
  },
  {
    id: "3",
    code: "CTK-9P-DCN-2024",
    name: "Điện công nghiệp (hệ 9+)",
    major: "Điện công nghiệp",
    eduSystem: "9_cong_10",
    department: "Khoa Điện – Điện tử",
    totalUnits: 1560,
    unitType: "gio",
    duration: "3 năm",
    status: "active",
    effectiveYear: 2024,
    issuedBy: "Sở LĐTBXH Khánh Hòa",
    decisionNo: "45/QĐ-SLĐTBXH",
    createdAt: "2024-03-05",
    updatedAt: "2024-08-15",
    terms: [
      {
        id: 1,
        label: "Năm 1 – HK1",
        modules: [
          {
            id: "d1",
            code: "MH01",
            name: "Giáo dục chính trị",
            units: 60,
            unitType: "gio",
            theory: 45,
            practice: 15,
            type: "chung",
            semester: 1,
          },
          {
            id: "d2",
            code: "MĐ02",
            name: "An toàn lao động điện",
            units: 30,
            unitType: "gio",
            theory: 15,
            practice: 15,
            type: "co_so",
            semester: 1,
          },
          {
            id: "d3",
            code: "MĐ03",
            name: "Điện kỹ thuật cơ bản",
            units: 90,
            unitType: "gio",
            theory: 30,
            practice: 60,
            type: "co_so",
            semester: 1,
            isKey: true,
          },
          {
            id: "d4",
            code: "MĐ04",
            name: "Đo lường điện",
            units: 60,
            unitType: "gio",
            theory: 15,
            practice: 45,
            type: "co_so",
            semester: 1,
            isKey: true,
          },
        ],
      },
      {
        id: 2,
        label: "Năm 1 – HK2",
        modules: [
          {
            id: "d5",
            code: "MĐ05",
            name: "Máy điện 1",
            units: 90,
            unitType: "gio",
            theory: 30,
            practice: 60,
            type: "chuyen_mon",
            semester: 2,
            prerequisite: ["MĐ03"],
            isKey: true,
          },
          {
            id: "d6",
            code: "MĐ06",
            name: "Trang bị điện công nghiệp",
            units: 90,
            unitType: "gio",
            theory: 30,
            practice: 60,
            type: "chuyen_mon",
            semester: 2,
            isKey: true,
          },
          {
            id: "d7",
            code: "MĐ07",
            name: "Điện tử cơ bản",
            units: 90,
            unitType: "gio",
            theory: 30,
            practice: 60,
            type: "co_so",
            semester: 2,
          },
        ],
      },
      {
        id: 3,
        label: "Thực tập sản xuất",
        internship: true,
        modules: [
          {
            id: "d8",
            code: "TT01",
            name: "Thực tập tại cơ sở sản xuất",
            units: 200,
            unitType: "gio",
            theory: 0,
            practice: 200,
            type: "thuc_tap",
            semester: 3,
            isKey: true,
          },
        ],
      },
    ],
  },
  {
    id: "4",
    code: "CTK-ĐHLK-QT-2023",
    name: "Quản trị kinh doanh (ĐH liên kết)",
    major: "Quản trị kinh doanh",
    eduSystem: "dai_hoc_lien_ket",
    department: "Khoa Kinh tế",
    totalUnits: 128,
    unitType: "tin_chi",
    duration: "4 năm",
    status: "active",
    effectiveYear: 2023,
    issuedBy: "ĐH Nha Trang (liên kết)",
    decisionNo: "512/QĐ-ĐHNT",
    createdAt: "2023-08-01",
    updatedAt: "2024-01-10",
    terms: [],
  },
  {
    id: "5",
    code: "CTK-DNNH-HAN-2024",
    name: "Hàn điện cơ bản",
    major: "Hàn điện",
    eduSystem: "day_nghe_ngan_han",
    department: "Khoa Cơ khí",
    totalUnits: 240,
    unitType: "gio",
    duration: "3 tháng",
    status: "active",
    effectiveYear: 2024,
    issuedBy: "Trường (tự ban hành)",
    decisionNo: "08/QĐ-TCN",
    createdAt: "2024-04-01",
    updatedAt: "2024-04-01",
    terms: [
      {
        id: 1,
        label: "Giai đoạn 1 – Cơ bản",
        modules: [
          {
            id: "h1",
            code: "MĐ01",
            name: "An toàn hàn",
            units: 16,
            unitType: "gio",
            theory: 8,
            practice: 8,
            type: "chung",
            semester: 1,
          },
          {
            id: "h2",
            code: "MĐ02",
            name: "Hàn hồ quang – Mối hàn bằng",
            units: 60,
            unitType: "gio",
            theory: 10,
            practice: 50,
            type: "thuc_hanh",
            semester: 1,
            isKey: true,
          },
          {
            id: "h3",
            code: "MĐ03",
            name: "Hàn hồ quang – Mối hàn đứng",
            units: 60,
            unitType: "gio",
            theory: 5,
            practice: 55,
            type: "thuc_hanh",
            semester: 1,
            isKey: true,
          },
        ],
      },
      {
        id: 2,
        label: "Giai đoạn 2 – Tổng hợp & Thi",
        modules: [
          {
            id: "h4",
            code: "MĐ04",
            name: "Thực hành ghép cấu kiện thép",
            units: 80,
            unitType: "gio",
            theory: 0,
            practice: 80,
            type: "thuc_hanh",
            semester: 2,
            isKey: true,
          },
          {
            id: "h5",
            code: "KT01",
            name: "Kiểm tra tay nghề – Thi tốt nghiệp",
            units: 24,
            unitType: "gio",
            theory: 4,
            practice: 20,
            type: "thuc_tap",
            semester: 2,
            isKey: true,
          },
        ],
      },
    ],
  },
  {
    id: "6",
    code: "CTK-DNSC-MAY-2025",
    name: "May công nghiệp",
    major: "May công nghiệp",
    eduSystem: "day_nghe_so_cap",
    department: "Khoa May – Thời trang",
    totalUnits: 120,
    unitType: "gio",
    duration: "1.5 tháng",
    status: "draft",
    effectiveYear: 2025,
    issuedBy: "Trường (đang soạn thảo)",
    decisionNo: "—",
    createdAt: "2025-01-15",
    updatedAt: "2025-02-10",
    terms: [],
  },
];
