import type { Exemption } from "./mockType";

export const exemptionsData: Exemption[] = [
  {
    id: "MG001",
    studentId: "SV001",
    studentName: "Nguyễn Văn An",
    class: "TCN21A",
    system: "Trung cấp nghề",
    type: "policy",
    typeLabel: "Con gia đình chính sách",
    amount: 6000000,
    percentage: 50,
    reason: "Con liệt sĩ, có giấy xác nhận từ UBND xã",
    documents: ["Giấy khai sinh", "Giấy xác nhận liệt sĩ", "Sổ hộ khẩu"],
    status: "approved",
    requestDate: "2026-01-10",
    reviewDate: "2026-01-15",
    reviewer: "Trần Văn B",
    reviewNote: "Đủ điều kiện, phê duyệt",
    phone: "0901234567",
    totalFee: 12000000,
  },
  {
    id: "MG002",
    studentId: "SV002",
    studentName: "Trần Thị Bình",
    class: "SCN21B",
    system: "Sơ cấp nghề",
    type: "difficult",
    typeLabel: "Hoàn cảnh khó khăn",
    amount: 4000000,
    percentage: 50,
    reason: "Gia đình khó khăn, có giấy xác nhận hộ nghèo",
    documents: ["Giấy xác nhận hộ nghèo", "Sổ hộ khẩu"],
    status: "pending",
    requestDate: "2026-04-05",
    phone: "0902345678",
    totalFee: 8000000,
  },
  {
    id: "MG003",
    studentId: "SV003",
    studentName: "Lê Văn Cường",
    class: "DHLK21A",
    system: "Đại học liên kết",
    type: "excellent",
    typeLabel: "Học sinh giỏi",
    amount: 3000000,
    percentage: 20,
    reason: "Học sinh giỏi cấp tỉnh năm 2025",
    documents: ["Bằng khen học sinh giỏi", "Bảng điểm THPT"],
    status: "approved",
    requestDate: "2026-01-20",
    reviewDate: "2026-01-22",
    reviewer: "Trần Văn B",
    reviewNote: "Thành tích xuất sắc, được miễn giảm",
    phone: "0903456789",
    totalFee: 15000000,
  },
  {
    id: "MG004",
    studentId: "SV004",
    studentName: "Phạm Thị Dung",
    class: "9PLUS21A",
    system: "Hệ 9+",
    type: "orphan",
    typeLabel: "Trẻ mồ côi",
    amount: 10000000,
    percentage: 100,
    reason: "Mồ côi cả cha lẫn mẹ, đang ở trại trẻ mồ côi",
    documents: ["Giấy xác nhận mồ côi", "Giấy xác nhận từ trại"],
    status: "approved",
    requestDate: "2026-02-01",
    reviewDate: "2026-02-03",
    reviewer: "Trần Văn B",
    reviewNote: "Miễn 100% học phí",
    phone: "0904567890",
    totalFee: 10000000,
  },
  {
    id: "MG005",
    studentId: "SV005",
    studentName: "Hoàng Văn Em",
    class: "TCN21B",
    system: "Trung cấp nghề",
    type: "ethnic",
    typeLabel: "Dân tộc thiểu số",
    amount: 3600000,
    percentage: 30,
    reason: "Dân tộc thiểu số vùng cao",
    documents: ["CMND/CCCD", "Giấy xác nhận dân tộc"],
    status: "pending",
    requestDate: "2026-04-08",
    phone: "0905678901",
    totalFee: 12000000,
  },
  {
    id: "MG006",
    studentId: "SV006",
    studentName: "Võ Thị Phương",
    class: "SCN21C",
    system: "Sơ cấp nghề",
    type: "disability",
    typeLabel: "Người khuyết tật",
    amount: 6400000,
    percentage: 80,
    reason: "Khuyết tật vận động, có sổ khuyết tật",
    documents: ["Sổ khuyết tật", "Giấy khám sức khỏe"],
    status: "rejected",
    requestDate: "2026-03-15",
    reviewDate: "2026-03-20",
    reviewer: "Trần Văn B",
    reviewNote: "Hồ sơ không đầy đủ, cần bổ sung",
    phone: "0906789012",
    totalFee: 8000000,
  },
  {
    id: "MG007",
    studentId: "SV007",
    studentName: "Đỗ Văn Giang",
    class: "TCN21C",
    system: "Trung cấp nghề",
    type: "policy",
    typeLabel: "Con gia đình chính sách",
    amount: 4800000,
    percentage: 40,
    reason: "Con thương binh hạng 1/4",
    documents: ["Sổ thương binh của cha", "Giấy khai sinh"],
    status: "pending",
    requestDate: "2026-04-09",
    phone: "0907890123",
    totalFee: 12000000,
  },
];

export const exemptionTypes = [
  { value: "all", label: "Tất cả loại", color: "gray" },
  { value: "policy", label: "Gia đình chính sách", color: "red" },
  { value: "difficult", label: "Hoàn cảnh khó khăn", color: "orange" },
  { value: "excellent", label: "Học sinh giỏi", color: "yellow" },
  { value: "orphan", label: "Trẻ mồ côi", color: "purple" },
  { value: "ethnic", label: "Dân tộc thiểu số", color: "blue" },
  { value: "disability", label: "Người khuyết tật", color: "pink" },
];
