import type { HocSinh } from "../mockType";

export const MOCK: HocSinh = {
  id: "1",
  maSoHocSinh: "TCN2024-0142",
  hoTen: "Nguyễn Thị Minh Châu",
  ngaySinh: "2006-03-15",
  gioiTinh: "Nữ",
  danToc: "Kinh",
  tonGiao: "Không",
  cccd: "079206012345",
  ngayCap: "2022-08-20",
  noiCap: "Cục Cảnh sát QLHC về TTXH",
  diaChiThuongTru: "45 Đường Lê Lợi, Phường Vĩnh Hải, TP. Nha Trang, Khánh Hòa",
  diaChiTamTru: "12/3 Hẻm 5, Phường Phước Tân, TP. Nha Trang",
  soDienThoai: "0901 234 567",
  email: "minhchau.nguyen@email.com",
  hoTenCha: "Nguyễn Văn Hùng",
  sdtCha: "0912 345 678",
  ngheNghiepCha: "Thợ hồ",
  hoTenMe: "Trần Thị Lan",
  sdtMe: "0923 456 789",
  ngheNghiepMe: "Nội trợ",
  nguoiLienHeKhac: "Nguyễn Văn Minh (Anh trai)",
  sdtLienHe: "0934 567 890",
  heDaoTao: "Trung cấp nghề",
  nganh: "Kỹ thuật May",
  chuyenNganh: "May thời trang",
  lop: "TCN-MAY-24A",
  khoaHoc: "2024 – 2026",
  namNhapHoc: 2024,
  trangThai: "Đang học",
  hocBongHienTai: "Hỗ trợ chi phí học nghề (Chính sách Nhà nước)",
  nhomMau: "A+",
  chieuCao: 158,
  canNang: 50,
  tinhTrangSucKhoe: "Bình thường, không dị tật",
  daNopHoSo: [
    "Đơn xin học",
    "Bản sao CCCD",
    "Học bạ THCS (có công chứng)",
    "Ảnh 3×4 (6 tấm)",
    "Giấy khai sinh (bản sao)",
    "Sổ hộ khẩu (bản sao)",
  ],
  chuaNopHoSo: [
    "Giấy khám sức khỏe",
    "Bằng tốt nghiệp THCS (bản sao công chứng)",
  ],
  ghiChu:
    "Học sinh thuộc diện chính sách, được miễn 100% học phí theo Nghị quyết 46/NQ-CP.",
};
