import type { UserResponse } from "../types/User.types";

export const SAMPLE_USERS: UserResponse[] = [
  {
    id: 1,
    name: "Nguyễn Văn Thắng",
    email: "thang.nv@truong.edu.vn",
    phoneNumber: "0901234567",
    role: "TEACHER",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2018-08-01"),
    staffProfile: {
      staffCode: "BGH001",
      position: "PRINCIPAL",
      department: "MANAGEMENT",
      additionalPositions: [],
      specialization: "Văn học",
      qualification: "Tiến sĩ Ngữ văn",
      joinDate: new Date("2010-08-01"),
      contractType: "FULL_TIME",
    },
  },
  {
    id: 2,
    name: "Trần Thị Hương",
    email: "huong.tt@truong.edu.vn",
    phoneNumber: "0902345678",
    role: "TEACHER",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2015-08-01"),
    staffProfile: {
      staffCode: "BGH002",
      position: "VICE_PRINCIPAL",
      department: "MANAGEMENT",
      additionalPositions: ["HEAD_OF_DEPARTMENT"],
      specialization: "Toán học",
      qualification: "Thạc sĩ Toán",
      joinDate: new Date("2008-08-01"),
      contractType: "FULL_TIME",
    },
  },
  {
    id: 3,
    name: "Lê Minh Khoa",
    email: "khoa.lm@truong.edu.vn",
    phoneNumber: "0903456789",
    role: "TEACHER",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2019-08-01"),
    staffProfile: {
      staffCode: "GV001",
      position: "TEACHER",
      department: "MATH",
      additionalPositions: ["HOMEROOM_TEACHER"],
      specialization: "Toán - Lý",
      qualification: "Thạc sĩ Toán",
      joinDate: new Date("2015-08-01"),
      contractType: "FULL_TIME",
    },
  },
  {
    id: 4,
    name: "Phạm Thị Lan",
    email: "lan.pt@truong.edu.vn",
    phoneNumber: "0904567890",
    role: "TEACHER",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2020-01-01"),
    staffProfile: {
      staffCode: "GV002",
      position: "HEAD_OF_DEPARTMENT",
      department: "ENGLISH",
      additionalPositions: [],
      specialization: "Tiếng Anh",
      qualification: "Cử nhân Tiếng Anh",
      joinDate: new Date("2012-08-01"),
      contractType: "FULL_TIME",
    },
  },
  {
    id: 5,
    name: "Đỗ Thanh Bình",
    email: "binh.dt@truong.edu.vn",
    phoneNumber: "0905678901",
    role: "TEACHER",
    avatarUrl: null,
    status: "inactive",
    createdAt: new Date("2021-08-01"),
    staffProfile: {
      staffCode: "GV003",
      position: "TEACHER",
      department: "SCIENCE",
      additionalPositions: [],
      specialization: "Vật lý - Hoá học",
      qualification: "Cử nhân Sư phạm",
      joinDate: new Date("2020-08-01"),
      contractType: "PART_TIME",
    },
  },
  {
    id: 6,
    name: "Ngô Thị Cúc",
    email: "cuc.nt@truong.edu.vn",
    phoneNumber: "0906789012",
    role: "STAFF",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2017-03-01"),
    staffProfile: {
      staffCode: "KT001",
      position: "CHIEF_ACCOUNTANT",
      department: "ACCOUNTING",
      additionalPositions: [],
      specialization: "Kế toán tài chính",
      qualification: "Cử nhân Kế toán",
      joinDate: new Date("2013-03-01"),
      contractType: "FULL_TIME",
    },
  },
  {
    id: 7,
    name: "Vũ Hải Nam",
    email: "nam.vh@truong.edu.vn",
    phoneNumber: "0907890123",
    role: "STAFF",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2022-06-01"),
    staffProfile: {
      staffCode: "HC001",
      position: "ADMIN_MANAGER",
      department: "ADMINISTRATION",
      additionalPositions: [],
      specialization: null,
      qualification: "Cử nhân Quản lý",
      joinDate: new Date("2019-06-01"),
      contractType: "FULL_TIME",
    },
  },
  {
    id: 8,
    name: "Bùi Thị Dung",
    email: "dung.bt@truong.edu.vn",
    phoneNumber: "0908901234",
    role: "STAFF",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2023-01-01"),
    staffProfile: {
      staffCode: "IT001",
      position: "IT_OFFICER",
      department: "IT",
      additionalPositions: [],
      specialization: "Quản trị mạng",
      qualification: "Kỹ sư CNTT",
      joinDate: new Date("2022-09-01"),
      contractType: "FULL_TIME",
    },
  },
  {
    id: 9,
    name: "Trịnh Văn An",
    email: "an.tv@truong.edu.vn",
    phoneNumber: "0909012345",
    role: "ADMIN",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2016-01-01"),
    staffProfile: null,
  },
  {
    id: 10,
    name: "Nguyễn Thị Mai",
    email: "mai.nt.10a1@truong.edu.vn",
    phoneNumber: "0910123456",
    role: "STUDENT",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2024-09-01"),
    studentProfile: {
      studentCode: "HS2024001",
      dateOfBirth: new Date("2008-05-15"),
      gender: "FEMALE",
      address: "123 Nguyễn Huệ, Nha Trang",
      classId: 1,
      className: "10A1",
      enrollmentYear: 2024,
      status: "STUDYING",
    },
  },
  {
    id: 11,
    name: "Phạm Văn Hùng",
    email: "hung.pv.11b2@truong.edu.vn",
    phoneNumber: "0911234567",
    role: "STUDENT",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2023-09-01"),
    studentProfile: {
      studentCode: "HS2023045",
      dateOfBirth: new Date("2007-11-22"),
      gender: "MALE",
      address: "456 Lê Lợi, Nha Trang",
      classId: 2,
      className: "11B2",
      enrollmentYear: 2023,
      status: "STUDYING",
    },
  },
  {
    id: 12,
    name: "Lê Thị Thu",
    email: "thu.lt.12a1@truong.edu.vn",
    phoneNumber: "0912345678",
    role: "STUDENT",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2022-09-01"),
    studentProfile: {
      studentCode: "HS2022012",
      dateOfBirth: new Date("2006-03-08"),
      gender: "FEMALE",
      address: "789 Trần Phú, Nha Trang",
      classId: 3,
      className: "12A1",
      enrollmentYear: 2022,
      status: "STUDYING",
    },
  },
  {
    id: 13,
    name: "Cao Văn Đức",
    email: "duc.cv@gmail.com",
    phoneNumber: "0913456789",
    role: "PARENT",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2024-09-01"),
    parentProfile: {
      occupation: "Kỹ sư xây dựng",
      relationship: "FATHER",
      children: [
        {
          studentCode: "HS2024001",
          name: "Nguyễn Thị Mai",
          className: "10A1",
          classId: 1,
        },
      ],
    },
  },
  {
    id: 14,
    name: "Hoàng Thị Yến",
    email: "yen.ht@gmail.com",
    phoneNumber: "0914567890",
    role: "PARENT",
    avatarUrl: null,
    status: "active",
    createdAt: new Date("2023-09-01"),
    parentProfile: {
      occupation: "Giáo viên tiểu học",
      relationship: "MOTHER",
      children: [
        {
          studentCode: "HS2023045",
          name: "Phạm Văn Hùng",
          className: "11B2",
          classId: 2,
        },
      ],
    },
  },
  {
    id: 15,
    name: "Đinh Văn Sơn",
    email: "son.dv@truong.edu.vn",
    phoneNumber: "0915678901",
    role: "STAFF",
    avatarUrl: null,
    status: "locked",
    createdAt: new Date("2020-01-01"),
    staffProfile: {
      staffCode: "HC002",
      position: "ADMIN_OFFICER",
      department: "ADMINISTRATION",
      additionalPositions: [],
      specialization: null,
      qualification: "Trung cấp",
      joinDate: new Date("2019-01-01"),
      contractType: "CONTRACT",
    },
  },
];
