export const MOCK_SYSTEM_LOGS = [
  {
    id: "LOG-001",
    time: "2024-05-22 14:30:05",
    user: "Nguyễn Văn Quản Trị",
    role: "Admin",
    type: "UPDATE",
    action: "Cập nhật lớp học",
    content: "Thay đổi sĩ số lớp K20-CNTT1 từ 30 lên 40 sinh viên.",
  },
  {
    id: "LOG-002",
    time: "2024-05-22 13:15:20",
    user: "Trần Thị Giáo Viên",
    role: "Teacher",
    type: "LOGIN",
    action: "Đăng nhập",
    content: "Đăng nhập hệ thống thành công từ IP 192.168.1.15.",
  },
  {
    id: "LOG-003",
    time: "2024-05-22 11:00:45",
    user: "Lê Văn Nhân Viên",
    role: "Staff",
    type: "CREATE",
    action: "Tạo mới sinh viên",
    content: "Thêm mới sinh viên 'Nguyễn Hoàng Nam' vào khóa K21.",
  },
  {
    id: "LOG-004",
    time: "2024-05-22 10:45:12",
    user: "Nguyễn Văn Quản Trị",
    role: "Admin",
    type: "DELETE",
    action: "Xóa học phần",
    content: "Xóa học phần 'Kỹ năng mềm' do trùng lặp mã môn học.",
  },
  {
    id: "LOG-005",
    time: "2024-05-22 09:30:00",
    user: "Phạm Minh Hoàng",
    role: "Teacher",
    type: "UPDATE",
    action: "Nhập điểm",
    content: "Hoàn tất nhập điểm thi kết thúc học kỳ 1 lớp K22-KT1.",
  },
  {
    id: "LOG-006",
    time: "2024-05-21 16:20:55",
    user: "Lê Văn Nhân Viên",
    role: "Staff",
    type: "UPDATE",
    action: "Chỉnh sửa hồ sơ",
    content:
      "Cập nhật số điện thoại và địa chỉ thường trú cho sinh viên Trần Đức Anh.",
  },
  {
    id: "LOG-007",
    time: "2024-05-21 15:40:10",
    user: "Nguyễn Văn Quản Trị",
    role: "Admin",
    type: "CREATE",
    action: "Cấp quyền",
    content: "Cấp quyền 'Quản lý tài chính' cho nhân viên Trần Thị Thu.",
  },
  {
    id: "LOG-008",
    time: "2024-05-21 14:05:30",
    user: "Hoàng Anh Tuấn",
    role: "Staff",
    type: "UPDATE",
    action: "Xác nhận học phí",
    content:
      "Xác nhận hoàn thành đóng học phí học kỳ 2 cho 15 sinh viên lớp K23-ĐN.",
  },
];
