import type { Application } from "./type";

export const majors = {
  "Trung cấp nghề": [
    "Công nghệ kỹ thuật ô tô",
    "Kỹ thuật hàn",
    "Điện công nghiệp",
    "Cơ khí chế tạo",
    "Kỹ thuật xây dựng",
  ],
  "Sơ cấp nghề": [
    "May công nghiệp",
    "Nấu ăn",
    "Điện dân dụng",
    "Sửa chữa điện tử",
    "Làm vườn",
  ],
  "Đại học liên kết": [
    "Quản trị kinh doanh",
    "Kế toán",
    "Công nghệ thông tin",
    "Marketing",
  ],
  "Hệ 9+": ["Điện tử công nghiệp", "Cơ khí ô tô", "Tin học ứng dụng"],
};

export const applicationsData: Application[] = [
  {
    id: "HS001",
    applicantName: "Nguyễn Văn An",
    birthDate: "2005-05-15",
    gender: "Nam",
    phone: "0901234567",
    email: "nguyenvanan@email.com",
    address: "Quận 1, TP.HCM",
    idCard: "079205012345",
    batch: "dot1_2026",
    batchLabel: "Đợt 1 - Năm 2026",
    system: "Trung cấp nghề",
    major: "Công nghệ kỹ thuật ô tô",
    graduationYear: "2023",
    previousSchool: "THPT Lê Quý Đôn",
    gpa: 7.8,
    status: "approved",
    submitDate: "2026-03-10",
    reviewDate: "2026-03-15",
    reviewer: "Trần Văn B",
    documents: [
      { name: "Bằng tốt nghiệp THPT", uploaded: true },
      { name: "Học bạ THPT", uploaded: true },
      { name: "Giấy khai sinh", uploaded: true },
      { name: "CMND/CCCD", uploaded: true },
      { name: "Ảnh 3x4", uploaded: true },
    ],
    notes: "Hồ sơ đầy đủ, đạt yêu cầu",
  },
  {
    id: "HS002",
    applicantName: "Trần Thị Bình",
    birthDate: "2008-08-20",
    gender: "Nữ",
    phone: "0902345678",
    email: "tranthib@email.com",
    address: "Quận 3, TP.HCM",
    idCard: "079208012346",
    batch: "dot1_2026",
    batchLabel: "Đợt 1 - Năm 2026",
    system: "Sơ cấp nghề",
    major: "May công nghiệp",
    graduationYear: "2024",
    previousSchool: "THCS Nguyễn Du",
    gpa: 7.0,
    status: "reviewing",
    submitDate: "2026-04-05",
    documents: [
      { name: "Bằng tốt nghiệp THCS", uploaded: true },
      { name: "Học bạ THCS", uploaded: true },
      { name: "Giấy khai sinh", uploaded: true },
      { name: "CMND/CCCD", uploaded: false },
      { name: "Ảnh 3x4", uploaded: true },
    ],
  },
  {
    id: "HS003",
    applicantName: "Lê Văn Cường",
    birthDate: "2005-12-10",
    gender: "Nam",
    phone: "0903456789",
    email: "levanc@email.com",
    address: "Quận 5, TP.HCM",
    idCard: "079205012347",
    batch: "dot2_2026",
    batchLabel: "Đợt 2 - Năm 2026",
    system: "Đại học liên kết",
    major: "Quản trị kinh doanh",
    graduationYear: "2023",
    previousSchool: "THPT Trần Hưng Đạo",
    gpa: 8.5,
    status: "submitted",
    submitDate: "2026-04-08",
    documents: [
      { name: "Bằng tốt nghiệp THPT", uploaded: true },
      { name: "Học bạ THPT", uploaded: true },
      { name: "Giấy chứng nhận ưu tiên", uploaded: true },
      { name: "Giấy khai sinh", uploaded: true },
      { name: "CMND/CCCD", uploaded: true },
      { name: "Ảnh 3x4", uploaded: true },
    ],
  },
  {
    id: "HS004",
    applicantName: "Phạm Thị Dung",
    birthDate: "2008-03-25",
    gender: "Nữ",
    phone: "0904567890",
    email: "phamthid@email.com",
    address: "Quận 7, TP.HCM",
    idCard: "079208012348",
    batch: "dot1_2026",
    batchLabel: "Đợt 1 - Năm 2026",
    system: "Hệ 9+",
    major: "Điện tử công nghiệp",
    graduationYear: "2024",
    previousSchool: "THCS Lê Lợi",
    gpa: 8.0,
    status: "approved",
    submitDate: "2026-03-20",
    reviewDate: "2026-03-25",
    reviewer: "Trần Văn B",
    documents: [
      { name: "Bằng tốt nghiệp THCS", uploaded: true },
      { name: "Học bạ THCS", uploaded: true },
      { name: "Giấy khai sinh", uploaded: true },
      { name: "CMND/CCCD", uploaded: true },
      { name: "Ảnh 3x4", uploaded: true },
    ],
    notes: "Học sinh giỏi, điểm cao",
  },
  {
    id: "HS005",
    applicantName: "Hoàng Văn Em",
    birthDate: "2005-07-18",
    gender: "Nam",
    phone: "0905678901",
    email: "hoangvane@email.com",
    address: "Quận 10, TP.HCM",
    idCard: "079205012349",
    batch: "dot1_2026",
    batchLabel: "Đợt 1 - Năm 2026",
    system: "Trung cấp nghề",
    major: "Kỹ thuật hàn",
    graduationYear: "2023",
    previousSchool: "THPT Nguyễn Thị Minh Khai",
    gpa: 6.5,
    status: "rejected",
    submitDate: "2026-03-12",
    reviewDate: "2026-03-18",
    reviewer: "Trần Văn B",
    documents: [
      { name: "Bằng tốt nghiệp THPT", uploaded: true },
      { name: "Học bạ THPT", uploaded: false },
      { name: "Giấy khai sinh", uploaded: true },
      { name: "CMND/CCCD", uploaded: true },
      { name: "Ảnh 3x4", uploaded: false },
    ],
    notes: "Hồ sơ thiếu học bạ và ảnh, không đạt",
  },
  {
    id: "HS006",
    applicantName: "Võ Thị Phương",
    birthDate: "2006-11-30",
    gender: "Nữ",
    phone: "0906789012",
    email: "vothip@email.com",
    address: "Quận 6, TP.HCM",
    idCard: "079206012350",
    batch: "dot2_2026",
    batchLabel: "Đợt 2 - Năm 2026",
    system: "Sơ cấp nghề",
    major: "Nấu ăn",
    graduationYear: "2024",
    previousSchool: "THCS Võ Thị Sáu",
    gpa: 7.5,
    status: "submitted",
    submitDate: "2026-04-09",
    documents: [
      { name: "Bằng tốt nghiệp THCS", uploaded: true },
      { name: "Học bạ THCS", uploaded: true },
      { name: "Giấy khai sinh", uploaded: true },
      { name: "CMND/CCCD", uploaded: true },
      { name: "Ảnh 3x4", uploaded: true },
    ],
  },
];
