/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FindAll"];
        put?: never;
        post: operations["Create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["QueryUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FindById"];
        put: operations["Update"];
        post?: never;
        delete: operations["Delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FindAll"];
        put?: never;
        post: operations["Create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SearchStudent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FindById"];
        put: operations["Update"];
        post?: never;
        delete: operations["Delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/majors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FindAll"];
        put?: never;
        post: operations["Create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/majors/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SearchMajor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/majors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FindById"];
        put: operations["Update"];
        post?: never;
        delete: operations["Delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lấy danh sách toàn bộ khoa */
        get: operations["GetAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lấy chi tiết một khoa theo ID */
        get: operations["GetById"];
        /** @description Cập nhật thông tin khoa */
        put: operations["Update"];
        post?: never;
        /** @description Xóa một khoa khỏi hệ thống */
        delete: operations["Delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Tạo mới một khoa */
        post: operations["Create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        "_36_Enums.RoleType": "ADMIN" | "STAFF" | "STUDENT" | "USER";
        RoleType: components["schemas"]["_36_Enums.RoleType"];
        CreateUserDTO: {
            username: string;
            password: string;
            email?: string;
            role?: components["schemas"]["RoleType"];
        };
        /** @description From T, pick a set of properties whose keys are in the union K */
        "Pick_User.address-or-birthday-or-email-or-fullName-or-gender-or-isActive-or-phone-or-username-or-createdAt-or-updatedAt-or-id-or-role_": {
            id: string;
            username: string;
            email: string;
            role: components["schemas"]["_36_Enums.RoleType"];
            fullName: string;
            gender: string;
            phone: string;
            /** Format: date-time */
            birthday: string;
            address: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UserResponse: components["schemas"]["Pick_User.address-or-birthday-or-email-or-fullName-or-gender-or-isActive-or-phone-or-username-or-createdAt-or-updatedAt-or-id-or-role_"];
        PaginationResponse_UserResponse_: {
            data: components["schemas"]["UserResponse"][];
            /** Format: double */
            total: number;
            /** Format: double */
            page: number;
            /** Format: double */
            limit: number;
        };
        UpdateUserDTO: {
            username?: string;
            password?: string;
            email?: string;
            role?: components["schemas"]["RoleType"];
            isActive?: boolean;
        };
        /** @enum {string} */
        "_36_Enums.StudentStatus": "STUDYING" | "DROPPED" | "SUSPENDED" | "GRADUATED";
        StudentStatus: components["schemas"]["_36_Enums.StudentStatus"];
        CreateStudentDTO: {
            studentCode: string;
            fullName: string;
            /** Format: date-time */
            birthday: string;
            gender: string;
            phone?: string;
            email?: string;
            address?: string;
            citizenId?: string;
            /** Format: double */
            majorId: number;
            /** Format: double */
            classId?: number;
            /** Format: double */
            userId?: number;
            status?: components["schemas"]["StudentStatus"];
        };
        StudentResponse: {
            /** Format: double */
            id: number;
            studentCode: string;
            fullName: string;
            email?: string | null;
            status: components["schemas"]["StudentStatus"];
            major: {
                name: string;
                /** Format: double */
                id: number;
            };
            class?: {
                name: string;
                /** Format: double */
                id: number;
            } | null;
        };
        PaginationResponse_StudentResponse_: {
            data: components["schemas"]["StudentResponse"][];
            /** Format: double */
            total: number;
            /** Format: double */
            page: number;
            /** Format: double */
            limit: number;
        };
        UpdateStudentDTO: {
            fullName?: string;
            /** Format: date-time */
            birthday?: string;
            gender?: string;
            phone?: string;
            email?: string;
            address?: string;
            citizenId?: string;
            /** Format: double */
            majorId?: number;
            /** Format: double */
            classId?: number;
            /** Format: double */
            userId?: number;
            status?: components["schemas"]["StudentStatus"];
        };
        CreateMajorDTO: {
            name: string;
            code: string;
            /** Format: double */
            departmentId: number;
        };
        UpdateMajorDTO: {
            name?: string;
            code?: string;
            /** Format: double */
            departmentId?: number;
        };
        "DefaultSelection_Prisma._36_DepartmentPayload_": {
            code: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
        };
        /** @description Model Department */
        Department: components["schemas"]["DefaultSelection_Prisma._36_DepartmentPayload_"];
        DepartmentCreateRequest: {
            name: string;
            code: string;
        };
        DepartmentUpdateRequest: {
            name?: string;
            code?: string;
        };
        LoginResponse: {
            message: string;
            user: {
                fullName: string;
                email: string;
                username: string;
                id: string;
            };
            accessToken: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        RegisterResponse: {
            message: string;
            user: components["schemas"]["UserResponse"];
        };
        RegisterRequest: {
            username: string;
            password: string;
            confirmPassword: string;
            email?: string | null;
            role: components["schemas"]["RoleType"];
            fullName?: string | null;
            gender?: string | null;
            address?: string | null;
            phone?: string | null;
            /** Format: date-time */
            birthday?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    FindAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        updatedAt: string;
                        /** Format: date-time */
                        createdAt: string;
                        isActive: boolean;
                        address: string;
                        /** Format: date-time */
                        birthday: string;
                        phone: string;
                        gender: string;
                        fullName: string;
                        role: components["schemas"]["_36_Enums.RoleType"];
                        email: string;
                        password: string;
                        username: string;
                        id: string;
                    }[];
                };
            };
        };
    };
    Create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDTO"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        updatedAt: string;
                        /** Format: date-time */
                        createdAt: string;
                        isActive: boolean;
                        address: string;
                        /** Format: date-time */
                        birthday: string;
                        phone: string;
                        gender: string;
                        fullName: string;
                        role: components["schemas"]["_36_Enums.RoleType"];
                        email: string;
                        password: string;
                        username: string;
                        id: string;
                    };
                };
            };
        };
    };
    QueryUser: {
        parameters: {
            query?: {
                email?: string;
                username?: string;
                roleName?: components["schemas"]["RoleType"];
                isActive?: boolean;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponse_UserResponse_"];
                };
            };
        };
    };
    FindById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        updatedAt: string;
                        /** Format: date-time */
                        createdAt: string;
                        isActive: boolean;
                        address: string;
                        /** Format: date-time */
                        birthday: string;
                        phone: string;
                        gender: string;
                        fullName: string;
                        role: components["schemas"]["_36_Enums.RoleType"];
                        email: string;
                        password: string;
                        username: string;
                        id: string;
                    };
                };
            };
        };
    };
    Update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDTO"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        updatedAt: string;
                        /** Format: date-time */
                        createdAt: string;
                        isActive: boolean;
                        address: string;
                        /** Format: date-time */
                        birthday: string;
                        phone: string;
                        gender: string;
                        fullName: string;
                        role: components["schemas"]["_36_Enums.RoleType"];
                        email: string;
                        password: string;
                        username: string;
                        id: string;
                    };
                };
            };
        };
    };
    Delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        updatedAt: string;
                        /** Format: date-time */
                        createdAt: string;
                        isActive: boolean;
                        address: string;
                        /** Format: date-time */
                        birthday: string;
                        phone: string;
                        gender: string;
                        fullName: string;
                        role: components["schemas"]["_36_Enums.RoleType"];
                        email: string;
                        password: string;
                        username: string;
                        id: string;
                    };
                };
            };
        };
    };
    FindAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": ({
                        class: {
                            majorId: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            createdAt: string;
                            id: string;
                            name: string;
                        };
                        major: {
                            code: string;
                            departmentId: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            createdAt: string;
                            id: string;
                            name: string;
                        };
                        user: {
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            createdAt: string;
                            isActive: boolean;
                            address: string;
                            /** Format: date-time */
                            birthday: string;
                            phone: string;
                            gender: string;
                            fullName: string;
                            role: components["schemas"]["_36_Enums.RoleType"];
                            email: string;
                            password: string;
                            username: string;
                            id: string;
                        };
                    } & {
                        classId: string;
                        majorId: string;
                        status: components["schemas"]["_36_Enums.StudentStatus"];
                        /** Format: date-time */
                        enrollmentDate: string;
                        citizenId: string;
                        studentCode: string;
                        userId: string;
                        /** Format: date-time */
                        updatedAt: string;
                        /** Format: date-time */
                        createdAt: string;
                        id: string;
                    })[];
                };
            };
        };
    };
    Create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentDTO"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        classId: string;
                        majorId: string;
                        status: components["schemas"]["_36_Enums.StudentStatus"];
                        /** Format: date-time */
                        enrollmentDate: string;
                        citizenId: string;
                        studentCode: string;
                        userId: string;
                        /** Format: date-time */
                        updatedAt: string;
                        /** Format: date-time */
                        createdAt: string;
                        id: string;
                    };
                };
            };
        };
    };
    SearchStudent: {
        parameters: {
            query?: {
                keyword?: string;
                status?: components["schemas"]["StudentStatus"];
                majorId?: number;
                classId?: number;
                isHasAccount?: boolean;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponse_StudentResponse_"];
                };
            };
        };
    };
    FindById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponse"];
                };
            };
        };
    };
    Update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStudentDTO"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        classId: string;
                        majorId: string;
                        status: components["schemas"]["_36_Enums.StudentStatus"];
                        /** Format: date-time */
                        enrollmentDate: string;
                        citizenId: string;
                        studentCode: string;
                        userId: string;
                        /** Format: date-time */
                        updatedAt: string;
                        /** Format: date-time */
                        createdAt: string;
                        id: string;
                    };
                };
            };
        };
    };
    Delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        classId: string;
                        majorId: string;
                        status: components["schemas"]["_36_Enums.StudentStatus"];
                        /** Format: date-time */
                        enrollmentDate: string;
                        citizenId: string;
                        studentCode: string;
                        userId: string;
                        /** Format: date-time */
                        updatedAt: string;
                        /** Format: date-time */
                        createdAt: string;
                        id: string;
                    };
                };
            };
        };
    };
    FindAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    Create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMajorDTO"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    SearchMajor: {
        parameters: {
            query?: {
                keyword?: string;
                departmentId?: number;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        data: ({
                            _count: {
                                /** Format: double */
                                classes: number;
                                /** Format: double */
                                students: number;
                            };
                            department: {
                                code: string;
                                /** Format: date-time */
                                updatedAt: string;
                                /** Format: date-time */
                                createdAt: string;
                                id: string;
                                name: string;
                            };
                        } & {
                            code: string;
                            departmentId: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            createdAt: string;
                            id: string;
                            name: string;
                        })[];
                    };
                };
            };
        };
    };
    FindById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    Update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMajorDTO"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    Delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    GetAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"][];
                };
            };
        };
    };
    GetById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"] | null;
                };
            };
        };
    };
    Update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentUpdateRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    Delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
        };
    };
}
