export const danhSachKhoa = [
  {
    tenKhoa: "Trình độ trung cấp",
    anh: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
    nganh: [
      "TC Hướng dẫn du lịch",
      "TC Kế toán doanh nghiệp",
      "TC tin học ứng dụng",
      "TC điện dân dụng và công nghiệp",
      "TC Tài chăm sóc sắc đẹp",
      "TC Kỹ thuật chế biến món ăn",
    ],
  },
  {
    tenKhoa: "Trình độ Cao đẳng (Liên kết)",
    anh: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80",
    nganh: ["CĐ điều dưỡng", "CĐ Chăm sóc sắc đẹp", "CĐ Kế toán doanh nghiệp"],
  },
  {
    tenKhoa: "Trình độ Đại học (Liên kết)",
    anh: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80",
    nganh: [
      "ĐH Ngôn ngữ Anh",
      "ĐH Công nghệ thông tin",
      "ĐH Quản trị kinh doanh",
      "ĐH Kế toán",
      "ĐH Luật",
      "ĐH Quản trị dịch vụ và Du lịch lữ hành",
      "ĐH Tài chính ngân hàng",
      "ĐH Thương mại điện tử",
      "ĐH Quản trị khách sạn",
      "ĐH Luật kinh tế",
    ],
  },
  {
    tenKhoa: "Trình độ Sơ cấp",
    anh: "https://images.unsplash.com/photo-1581092921461-39b9d08a9e24?w=800&q=80",
    nganh: [
      "SCN Kế toán doanh nghiệp",
      "SCN Sữa chữa ô tô",
      "SCN Nghiệp vụ An ninh Khách sạn",
      "SCN Quản lý Nhà hàng - Khách sạn",
      "SCN Nghiệp vụ buồng phòng khách sạn",
      "SCN Nghiệp vụ bếp",
      "SCN Nghiệp vụ lễ tân",
      "SCN Phục vụ khách hàng",
      "SCN Nghiệp vụ pha chế (Bartender)",
    ],
  },
  {
    tenKhoa: "Đào tạo nghề cho Bộ đội xuất ngũ",
    anh: "https://images.unsplash.com/photo-1581092921461-39b9d08a9e24?w=800&q=80",
    nganh: [
      "Nghề điện lạnh",
      "Nghề lắp đặt điện nội thất",
      "Nghề lắp đặt điện nước",
      "Nghề xây dựng",
      "Nghề hàn điện",
      "Nghề Kỹ thuật chế biến món Á",
      "Nghề kỹ thuật chế biến món Âu",
      "Nghề nghiệp vụ pha chế thức uống",
      "Nghề Quản lý nhà hàng",
      "Nghề kỹ thuật làm bánh",
    ],
  },
  {
    tenKhoa: "Bồi dưỡng kỹ năng nghiệp vụ quản lý",
    anh: "https://images.unsplash.com/photo-1581092921461-39b9d08a9e24?w=800&q=80",
    nganh: [
      "Quản lý chất lượng",
      "Quản lý nhân sự",
      "Quản lý, xây dựng chiến lược Kinh doanh",
      "Kiến thức kế toán dành cho lãnh đạo",
      "Kỹ năng thuyết trình trước đám đông",
    ],
  },
];
