export const HE_DAO_TAO = {
  "9plus": "Hệ 9+",
  trungcap: "Trung cấp nghề",
  caodang: "Cao đẳng",
  daihoc: "ĐH liên kết",
};

export const SAMPLE_DATA = [
  {
    ma: "9P-KT-K22A",
    ten: "Kế toán 9+ K22 – A",
    he: "9plus",
    khoa: "K2022",
    nganh: "Kế toán",
    chuyenNganh: "Kế toán DN",
    siso: 38,
    max: 40,
    status: "Đang học",
    gvcn: "Nguyễn Thị Hoa",
    phong: "A203",
    hinhThuc: "Tập trung",
  },
  {
    ma: "9P-KT-K22B",
    ten: "Kế toán 9+ K22 – B",
    he: "9plus",
    khoa: "K2022",
    nganh: "Kế toán",
    chuyenNganh: "Kế toán DN",
    siso: 36,
    max: 40,
    status: "Đang học",
    gvcn: "Trần Thị Mai",
    phong: "A204",
    hinhThuc: "Tập trung",
  },
  {
    ma: "9P-IT-K23A",
    ten: "CNTT 9+ K23 – A",
    he: "9plus",
    khoa: "K2023",
    nganh: "CNTT",
    chuyenNganh: "Lập trình web",
    siso: 32,
    max: 40,
    status: "Đang học",
    gvcn: "Trần Văn Minh",
    phong: "B101",
    hinhThuc: "Tập trung",
  },
  {
    ma: "9P-IT-K24A",
    ten: "CNTT 9+ K24 – A",
    he: "9plus",
    khoa: "K2024",
    nganh: "CNTT",
    chuyenNganh: "Lập trình web",
    siso: 28,
    max: 40,
    status: "Đang tuyển",
    gvcn: "Lê Hoàng Nam",
    phong: "B102",
    hinhThuc: "Tập trung",
  },
  {
    ma: "9P-DL-K23A",
    ten: "Du lịch 9+ K23 – A",
    he: "9plus",
    khoa: "K2023",
    nganh: "Du lịch",
    chuyenNganh: "Hướng dẫn viên",
    siso: 35,
    max: 40,
    status: "Đang học",
    gvcn: "Nguyễn Lan Anh",
    phong: "C201",
    hinhThuc: "Tập trung",
  },
  {
    ma: "9P-CK-K22A",
    ten: "Cơ khí 9+ K22 – A",
    he: "9plus",
    khoa: "K2022",
    nganh: "Cơ khí",
    chuyenNganh: "Cơ khí chế tạo",
    siso: 38,
    max: 40,
    status: "Đã kết thúc",
    gvcn: "Phạm Quốc Hùng",
    phong: "D101",
    hinhThuc: "Tập trung",
  },
  {
    ma: "TC-KT-K22A",
    ten: "Kế toán TC K22 – A",
    he: "trungcap",
    khoa: "K2022",
    nganh: "Kế toán",
    chuyenNganh: "Kế toán tổng hợp",
    siso: 42,
    max: 45,
    status: "Đang học",
    gvcn: "Phạm Thị Lan",
    phong: "A301",
    hinhThuc: "Tập trung",
  },
  {
    ma: "TC-KT-K22B",
    ten: "Kế toán TC K22 – B",
    he: "trungcap",
    khoa: "K2022",
    nganh: "Kế toán",
    chuyenNganh: "Kế toán tổng hợp",
    siso: 40,
    max: 45,
    status: "Đang học",
    gvcn: "Hoàng Thị Bình",
    phong: "A302",
    hinhThuc: "Tập trung",
  },
  {
    ma: "TC-DT-K23A",
    ten: "Điện tử TC K23 – A",
    he: "trungcap",
    khoa: "K2023",
    nganh: "Điện – Điện tử",
    chuyenNganh: "Điện tử công nghiệp",
    siso: 38,
    max: 40,
    status: "Đang học",
    gvcn: "Lê Thị Thu",
    phong: "D201",
    hinhThuc: "Tập trung",
  },
  {
    ma: "TC-DT-K23B",
    ten: "Điện tử TC K23 – B",
    he: "trungcap",
    khoa: "K2023",
    nganh: "Điện – Điện tử",
    chuyenNganh: "Điện tử công nghiệp",
    siso: 36,
    max: 40,
    status: "Đang học",
    gvcn: "Vũ Quang Sáng",
    phong: "D202",
    hinhThuc: "Tập trung",
  },
  {
    ma: "TC-CK-K22A",
    ten: "Cơ khí TC K22 – A",
    he: "trungcap",
    khoa: "K2022",
    nganh: "Cơ khí",
    chuyenNganh: "Hàn – cắt kim loại",
    siso: 40,
    max: 45,
    status: "Đã kết thúc",
    gvcn: "Phạm Quốc Hùng",
    phong: "D101",
    hinhThuc: "Tập trung",
  },
  {
    ma: "TC-IT-K24A",
    ten: "CNTT TC K24 – A",
    he: "trungcap",
    khoa: "K2024",
    nganh: "CNTT",
    chuyenNganh: "Lập trình ứng dụng",
    siso: 25,
    max: 40,
    status: "Đang tuyển",
    gvcn: "Trần Văn Minh",
    phong: "B201",
    hinhThuc: "Tập trung",
  },
  {
    ma: "TC-KT-K24A",
    ten: "Kế toán TC K24 – A",
    he: "trungcap",
    khoa: "K2024",
    nganh: "Kế toán",
    chuyenNganh: "Kế toán thuế",
    siso: 20,
    max: 45,
    status: "Đang tuyển",
    gvcn: "Chưa phân công",
    phong: "A401",
    hinhThuc: "Tập trung",
  },
  {
    ma: "TC-DL-K23A",
    ten: "Du lịch TC K23 – A",
    he: "trungcap",
    khoa: "K2023",
    nganh: "Du lịch",
    chuyenNganh: "Quản trị khách sạn",
    siso: 30,
    max: 40,
    status: "Đang học",
    gvcn: "Nguyễn Lan Anh",
    phong: "C301",
    hinhThuc: "Tập trung",
  },
  {
    ma: "CD-KT-K22A",
    ten: "Kế toán CĐ K22 – A",
    he: "caodang",
    khoa: "K2022",
    nganh: "Kế toán",
    chuyenNganh: "Kế toán DN",
    siso: 44,
    max: 50,
    status: "Đang học",
    gvcn: "Nguyễn Thị Hoa",
    phong: "A501",
    hinhThuc: "Tập trung",
  },
  {
    ma: "CD-IT-K23A",
    ten: "CNTT CĐ K23 – A",
    he: "caodang",
    khoa: "K2023",
    nganh: "CNTT",
    chuyenNganh: "Kỹ thuật phần mềm",
    siso: 38,
    max: 45,
    status: "Đang học",
    gvcn: "Trần Văn Minh",
    phong: "B301",
    hinhThuc: "Tập trung",
  },
  {
    ma: "CD-DT-K22A",
    ten: "Điện tử CĐ K22 – A",
    he: "caodang",
    khoa: "K2022",
    nganh: "Điện – Điện tử",
    chuyenNganh: "Điện tử viễn thông",
    siso: 40,
    max: 45,
    status: "Đã kết thúc",
    gvcn: "Lê Thị Thu",
    phong: "D301",
    hinhThuc: "Tập trung",
  },
  {
    ma: "CD-CK-K23A",
    ten: "Cơ khí CĐ K23 – A",
    he: "caodang",
    khoa: "K2023",
    nganh: "Cơ khí",
    chuyenNganh: "Cơ điện tử",
    siso: 35,
    max: 40,
    status: "Đang học",
    gvcn: "Phạm Quốc Hùng",
    phong: "D401",
    hinhThuc: "Vừa học vừa làm",
  },
  {
    ma: "CD-DL-K24A",
    ten: "Du lịch CĐ K24 – A",
    he: "caodang",
    khoa: "K2024",
    nganh: "Du lịch",
    chuyenNganh: "Quản trị lữ hành",
    siso: 18,
    max: 40,
    status: "Đang tuyển",
    gvcn: "Nguyễn Lan Anh",
    phong: "C401",
    hinhThuc: "Tập trung",
  },
  {
    ma: "DH-KT-K22A",
    ten: "Kế toán ĐH LK K22 – A",
    he: "daihoc",
    khoa: "K2022",
    nganh: "Kế toán",
    chuyenNganh: "Kế toán kiểm toán",
    siso: 55,
    max: 60,
    status: "Đang học",
    gvcn: "GS. Trần Đình Khoa",
    phong: "A601",
    hinhThuc: "Tập trung",
  },
  {
    ma: "DH-KT-K22B",
    ten: "Kế toán ĐH LK K22 – B",
    he: "daihoc",
    khoa: "K2022",
    nganh: "Kế toán",
    chuyenNganh: "Kế toán kiểm toán",
    siso: 52,
    max: 60,
    status: "Đang học",
    gvcn: "TS. Nguyễn Bảo Châu",
    phong: "A602",
    hinhThuc: "Tập trung",
  },
  {
    ma: "DH-IT-K23A",
    ten: "CNTT ĐH LK K23 – A",
    he: "daihoc",
    khoa: "K2023",
    nganh: "CNTT",
    chuyenNganh: "Công nghệ thông tin",
    siso: 48,
    max: 55,
    status: "Đang học",
    gvcn: "ThS. Lê Văn Đức",
    phong: "B401",
    hinhThuc: "Tập trung",
  },
  {
    ma: "DH-DL-K22A",
    ten: "Du lịch ĐH LK K22 – A",
    he: "daihoc",
    khoa: "K2022",
    nganh: "Du lịch",
    chuyenNganh: "Quản trị du lịch",
    siso: 50,
    max: 55,
    status: "Đã kết thúc",
    gvcn: "TS. Phạm Thu Hà",
    phong: "C501",
    hinhThuc: "Vừa học vừa làm",
  },
];
